spring:
    datasource:
        url: jdbc:h2:C:\Users\logonrmlocal\Documents\Git\library-batch-chunk\chuck;DB_CLOSE_ON_EXIT=FALSE
        username: fiap
        password: fiap

file:
    input: classpath:pessoas.txt